### ISSUE TITLE
http error 416

### ISSUE THREAD

**Issue by VitamintK** [EleutherAI/best-download#1] opened 2021-01-27 03:42 UTC
Just got this:  
(previously tried doing the same thing but the download errored out due to the directory not existing)

```
Downloading https://raw.githubusercontent.com/openai/gpt-3/master/data/two_digit_addition.jsonl
File already exists, resuming download.
Download error: 416 Client Error: Range Not Satisfiable for url: https://raw.githubusercontent.com/openai/gpt-3/master/data/two_digit_addition.jsonl
139kbyte [00:00, 799kbyte/s]
File already exists, resuming download.
Download error: 416 Client Error: Range Not Satisfiable for url: https://raw.githubusercontent.com/openai/gpt-3/master/data/two_digit_addition.jsonl
139kbyte [00:00, 742kbyte/s]
```

to repro:

```python
from best_download import download_file
download_file('https://raw.githubusercontent.com/openai/gpt-3/master/data/two_digit_addition.jsonl', 'test.test', None)
```

**Comment by researcher2** [comment] 2021-01-27 08:01
The problem is the result of automatic decompression built into requests, with the streamed data length being much larger then the Content-Length header. It will be a bit of work to get around this, in the mean time I'll remove the length check when dealing with gzip content.

**Comment by researcher2** [comment] 2021-01-27 08:09
Ok done, I'll leave this open for the proper fix.

**Comment by researcher2** [comment] 2021-06-18 03:35
Closing as gzip content encoding is now disabled in the rewrite.

**Closed as completed by researcher2** 2021-06-18 03:35 UTC
